# Enhanced GitZoom Lightning Push - Optimized single-command workflow
param(
    [string]$message = "Quick update",
    [switch]$EnableBatchOps,    # Kept for backward compatibility (always on now)
    [switch]$EnableParallel,    # Kept for backward compatibility (no-op)
    [switch]$Verbose
)

Write-Host "⚡ GitZoom Enhanced Lightning Push starting..." -ForegroundColor Cyan

# Check if we're in a git repository
if (-not (Test-Path ".git")) {
    Write-Host "❌ Not in a git repository!" -ForegroundColor Red
    Write-Host "💡 Tip: Run 'git init' to initialize a repository" -ForegroundColor Yellow
    exit 1
}

# Performance tracking
$totalStopwatch = [System.Diagnostics.Stopwatch]::StartNew()

# ============================================================================
# STAGING: Single-command add (fastest possible - one git process)
# ============================================================================
Write-Host "📦 Using optimized staging..." -ForegroundColor Yellow

# Quick check: anything to commit?
$statusOutput = git status --porcelain
if (-not $statusOutput) {
    Write-Host "✅ No changes to commit - you're already zoomed!" -ForegroundColor Green
    exit 0
}

$stageStopwatch = [System.Diagnostics.Stopwatch]::StartNew()

# Single git add -A: stages all changes (new, modified, deleted) in one process call
# This is faster than multiple type-grouped git add calls
git add -A

$stageStopwatch.Stop()

# Count staged files from the status output we already captured
$fileCount = @($statusOutput).Count
Write-Host "✅ Staged $fileCount files in $($stageStopwatch.ElapsedMilliseconds)ms" -ForegroundColor Green

if ($Verbose) {
    $statusOutput | ForEach-Object {
        $status = $_.Substring(0, 2).Trim()
        $file = $_.Substring(3)
        $label = switch ($status) { "M" {"modified"} "A" {"added"} "D" {"deleted"} "?" {"new"} default {$status} }
        Write-Host "  $label`: $file" -ForegroundColor Gray
    }
}

# ============================================================================
# COMMIT
# ============================================================================
Write-Host "💾 Committing changes..." -ForegroundColor Yellow
$commitStopwatch = [System.Diagnostics.Stopwatch]::StartNew()
git commit -m $message
$commitStopwatch.Stop()

if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Commit failed!" -ForegroundColor Red
    exit 1
}

Write-Host "✅ Commit completed in $($commitStopwatch.ElapsedMilliseconds)ms" -ForegroundColor Green

# ============================================================================
# PUSH TO REMOTE
# ============================================================================
Write-Host "🚀 Pushing to remote..." -ForegroundColor Yellow
$pushStopwatch = [System.Diagnostics.Stopwatch]::StartNew()

# Try to push to the current branch first
$currentBranch = git branch --show-current
git push origin $currentBranch

if ($LASTEXITCODE -ne 0) {
    # If that fails, try setting upstream
    Write-Host "🔗 Setting upstream and pushing..." -ForegroundColor Yellow
    git push --set-upstream origin $currentBranch
}

$pushStopwatch.Stop()

if ($LASTEXITCODE -eq 0) {
    $totalStopwatch.Stop()
    
    Write-Host "✅ Changes successfully pushed to GitHub!" -ForegroundColor Green
    Write-Host "⚡ Enhanced GitZoom Lightning Push completed!" -ForegroundColor Magenta
    
    # Performance summary
    Write-Host "`n📊 Performance Summary:" -ForegroundColor Cyan
    Write-Host "  Total Time: $($totalStopwatch.ElapsedMilliseconds)ms" -ForegroundColor White
    Write-Host "  Push Time: $($pushStopwatch.ElapsedMilliseconds)ms" -ForegroundColor White
    
    Write-Host "  Staging: single-command (git add -A) ✅" -ForegroundColor Green
    
    Write-Host "   Generated by Enhanced GitZoom - https://github.com/GaBe141/GitZoom" -ForegroundColor DarkGray
    
    # Performance recommendation
    if ($totalStopwatch.ElapsedMilliseconds -lt 1000) {
        Write-Host "🚀 Sub-second performance achieved!" -ForegroundColor Green
    } elseif ($totalStopwatch.ElapsedMilliseconds -lt 3000) {
        Write-Host "⚡ Great performance!" -ForegroundColor Yellow
    } else {
        Write-Host "💡 Consider enabling more optimizations for faster performance" -ForegroundColor Yellow
    }
    
} else {
    Write-Host "❌ Push failed!" -ForegroundColor Red
    Write-Host "💡 Check your internet connection and repository permissions" -ForegroundColor Yellow
    exit 1
}